name: Test Changes
on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/dacbd/gcpcc:${{ github.sha}}
  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Modify action.yml for test.
        run: |
          sed -i "s/  image:.*/  image: 'docker:\/\/ghcr.io\/dacbd\/gcpcc:${{ github.sha}}'/g" ./action.yml
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON_KEY }}
      - uses: './'
        id: gcpcc
      - name: Show output
        run: |
          echo "instance count: ${{ steps.gcpcc.outputs.total }}"

